repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: name-tests-test
      - id: sort-simple-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb=10000"]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
